# Generated by Django 4.2.3 on 2024-05-30 06:24

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
